server:
    port: 8001
logging:
    config: classpath:logback.xml
spring:
    application:
        name: dpd-site-chooser-backend-api
    jackson:
        default-property-inclusion: non_null
    liquibase:
        enabled: true
        change-log: classpath:db/liquibase_master.xml
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_BASE:fieldwire_challenge}?prepareThreshold=0
        username: ${DB_USR:postgres}
        password: ${DB_PWD:postgres}
        hikari:
            maximum-pool-size: 20
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
    servlet:
        multipart:
            enabled: true
            max-file-size: 10MB
            max-request-size: 10MB